# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 10:24
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='email',
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=datetime.datetime(2016, 4, 21, 10, 24, 34, 348150, tzinfo=utc), error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='house_number',
            field=models.IntegerField(default=0),
        ),
    ]
