# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0002_auto_20160421_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_admin',
            new_name='is_superuser',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='house_number',
            new_name='phone_number',
        ),
    ]
