# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0004_auto_20160422_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False, max_length=10),
        ),
    ]
