# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0003_auto_20160424_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debttype',
            old_name='slung',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True, verbose_name='Сумма'),
        ),
    ]
