# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0004_auto_20160425_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='imported_from',
            field=models.TextField(default=datetime.datetime(2016, 5, 4, 13, 5, 11, 821081, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
